<?php
/**
 * Register Custom Gutenberg Blocks
 *
 * @package Infinity_2025_Simple
 */

/**
 * Style Collector - Collect dynamic styles for clean HTML
 */
class Infinity_Style_Collector {
    private static $styles = array();

    /**
     * Add a style rule
     */
    public static function add_style( $selector, $rules ) {
        if ( ! empty( $rules ) ) {
            self::$styles[ $selector ] = $rules;
        }
    }

    /**
     * Get all collected styles
     */
    public static function get_styles() {
        return self::$styles;
    }

    /**
     * Clear all collected styles
     */
    public static function clear_styles() {
        self::$styles = array();
    }
}

/**
 * Generate CSS file from post content
 */
function infinity_generate_post_css( $post_id ) {
    // Skip autosaves and revisions
    if ( wp_is_post_autosave( $post_id ) || wp_is_post_revision( $post_id ) ) {
        return;
    }

    // Get post content
    $post = get_post( $post_id );
    if ( ! $post || empty( $post->post_content ) ) {
        return;
    }

    // Parse blocks
    $blocks = parse_blocks( $post->post_content );
    $css_rules = array();

    // Extract styles from infinity/container blocks
    infinity_extract_container_styles( $blocks, $css_rules );

    // Generate CSS file with proper formatting
    if ( ! empty( $css_rules ) ) {
        $css_content = "/**\n * Generated CSS for Post ID: {$post_id}\n * Auto-generated by Infinity Container blocks\n */\n\n";

        foreach ( $css_rules as $selector => $rules ) {
            $css_content .= $selector . " {\n";
            foreach ( $rules as $rule ) {
                $css_content .= "    " . $rule . ";\n";
            }
            $css_content .= "}\n\n";
        }

        // Save to file
        $css_dir = INFINITY_DIR . '/assets/css/pages';
        if ( ! file_exists( $css_dir ) ) {
            wp_mkdir_p( $css_dir );
        }

        $css_file = $css_dir . '/page-' . $post_id . '.css';
        file_put_contents( $css_file, $css_content );
    }
}

/**
 * Recursively extract styles from container blocks
 */
function infinity_extract_container_styles( $blocks, &$css_rules ) {
    foreach ( $blocks as $block ) {
        if ( $block['blockName'] === 'infinity/container' && ! empty( $block['attrs'] ) ) {
            $attrs = $block['attrs'];
            $rules = array();

            // Dimensions
            if ( ! empty( $attrs['width'] ) ) {
                $rules[] = 'width:' . esc_attr( $attrs['width'] );
                $rules[] = 'max-width:none';  // Override theme .container max-width

                // Also reset margin/padding from .container if no custom values set
                if ( empty( $attrs['marginLeft'] ) && empty( $attrs['marginRight'] ) ) {
                    $rules[] = 'margin-left:0';
                    $rules[] = 'margin-right:0';
                }
                if ( empty( $attrs['paddingLeft'] ) && empty( $attrs['paddingRight'] ) ) {
                    $rules[] = 'padding-left:0';
                    $rules[] = 'padding-right:0';
                }
            }
            if ( ! empty( $attrs['height'] ) ) {
                $rules[] = 'height:' . esc_attr( $attrs['height'] );
            }

            // Layout
            if ( ! empty( $attrs['display'] ) ) {
                $rules[] = 'display:' . esc_attr( $attrs['display'] );
            }
            if ( ! empty( $attrs['flexDirection'] ) ) {
                $rules[] = 'flex-direction:' . esc_attr( $attrs['flexDirection'] );
            }
            if ( ! empty( $attrs['justifyContent'] ) ) {
                $rules[] = 'justify-content:' . esc_attr( $attrs['justifyContent'] );
            }
            if ( ! empty( $attrs['alignItems'] ) ) {
                $rules[] = 'align-items:' . esc_attr( $attrs['alignItems'] );
            }
            if ( ! empty( $attrs['gap'] ) ) {
                $rules[] = 'gap:' . esc_attr( $attrs['gap'] );
            }
            if ( ! empty( $attrs['gridTemplateColumns'] ) ) {
                $rules[] = 'grid-template-columns:' . esc_attr( $attrs['gridTemplateColumns'] );
            }

            // Background
            if ( ! empty( $attrs['backgroundColor'] ) ) {
                $rules[] = 'background-color:' . esc_attr( $attrs['backgroundColor'] );
            }
            if ( ! empty( $attrs['backgroundImage'] ) ) {
                $rules[] = 'background-image:url(' . esc_url( $attrs['backgroundImage'] ) . ')';
                $rules[] = 'background-size:cover';
                $rules[] = 'background-position:center';
            }

            // Padding
            if ( ! empty( $attrs['paddingTop'] ) ) {
                $rules[] = 'padding-top:' . esc_attr( $attrs['paddingTop'] );
            }
            if ( ! empty( $attrs['paddingRight'] ) ) {
                $rules[] = 'padding-right:' . esc_attr( $attrs['paddingRight'] );
            }
            if ( ! empty( $attrs['paddingBottom'] ) ) {
                $rules[] = 'padding-bottom:' . esc_attr( $attrs['paddingBottom'] );
            }
            if ( ! empty( $attrs['paddingLeft'] ) ) {
                $rules[] = 'padding-left:' . esc_attr( $attrs['paddingLeft'] );
            }

            // Margin
            if ( ! empty( $attrs['marginTop'] ) ) {
                $rules[] = 'margin-top:' . esc_attr( $attrs['marginTop'] );
            }
            if ( ! empty( $attrs['marginRight'] ) ) {
                $rules[] = 'margin-right:' . esc_attr( $attrs['marginRight'] );
            }
            if ( ! empty( $attrs['marginBottom'] ) ) {
                $rules[] = 'margin-bottom:' . esc_attr( $attrs['marginBottom'] );
            }
            if ( ! empty( $attrs['marginLeft'] ) ) {
                $rules[] = 'margin-left:' . esc_attr( $attrs['marginLeft'] );
            }

            // Border
            if ( ! empty( $attrs['borderWidth'] ) && ! empty( $attrs['borderColor'] ) ) {
                $border_style = ! empty( $attrs['borderStyle'] ) ? esc_attr( $attrs['borderStyle'] ) : 'solid';
                $rules[] = 'border:' . esc_attr( $attrs['borderWidth'] ) . ' ' . $border_style . ' ' . esc_attr( $attrs['borderColor'] );
            }
            if ( ! empty( $attrs['borderRadius'] ) ) {
                $rules[] = 'border-radius:' . esc_attr( $attrs['borderRadius'] );
            }

            // Determine class
            if ( ! empty( $attrs['customClass'] ) ) {
                $selector = '.' . esc_attr( $attrs['customClass'] );
            } else {
                $selector = '.inf-' . substr( md5( serialize( $attrs ) ), 0, 8 );
            }

            if ( ! empty( $rules ) ) {
                $css_rules[ $selector ] = $rules;
            }
        }

        // Recursively process inner blocks
        if ( ! empty( $block['innerBlocks'] ) ) {
            infinity_extract_container_styles( $block['innerBlocks'], $css_rules );
        }
    }
}

/**
 * Hook: Generate CSS on post save
 */
add_action( 'save_post', 'infinity_generate_post_css', 10, 1 );

/**
 * Enqueue generated CSS file in head
 */
function infinity_enqueue_page_css() {
    if ( is_singular() ) {
        $post_id = get_the_ID();
        $css_file = INFINITY_DIR . '/assets/css/pages/page-' . $post_id . '.css';
        $css_url = INFINITY_URI . '/assets/css/pages/page-' . $post_id . '.css';

        if ( file_exists( $css_file ) ) {
            wp_enqueue_style( 'infinity-page-' . $post_id, $css_url, array(), filemtime( $css_file ) );
        }
    }
}
add_action( 'wp_enqueue_scripts', 'infinity_enqueue_page_css', 20 );


/**
 * Register block scripts and styles
 */
function infinity_register_block_assets() {
    // Register the block editor script
    wp_register_script(
        'infinity-container-editor',
        INFINITY_URI . '/inc/blocks/infinity-container/index.js',
        array( 'wp-blocks', 'wp-element', 'wp-editor', 'wp-block-editor', 'wp-components' ),
        INFINITY_VERSION,
        true
    );

    // Register the block style
    wp_register_style(
        'infinity-container-style',
        INFINITY_URI . '/inc/blocks/infinity-container/style.css',
        array(),
        INFINITY_VERSION
    );

    // Register the editor style
    wp_register_style(
        'infinity-container-editor-style',
        INFINITY_URI . '/inc/blocks/infinity-container/editor.css',
        array(),
        INFINITY_VERSION
    );
}
add_action( 'init', 'infinity_register_block_assets' );

/**
 * Register Infinity Container Block
 */
function infinity_register_blocks() {
    // Register Infinity Container block
    register_block_type( 'infinity/container', array(
        'editor_script'   => 'infinity-container-editor',
        'editor_style'    => 'infinity-container-editor-style',
        'style'           => 'infinity-container-style',
        'render_callback' => 'infinity_container_render_callback',
        'attributes'      => array(
            'customClass'        => array( 'type' => 'string', 'default' => '' ),
            'width'              => array( 'type' => 'string', 'default' => '' ),
            'height'             => array( 'type' => 'string', 'default' => '' ),
            'paddingTop'         => array( 'type' => 'string', 'default' => '' ),
            'paddingRight'       => array( 'type' => 'string', 'default' => '' ),
            'paddingBottom'      => array( 'type' => 'string', 'default' => '' ),
            'paddingLeft'        => array( 'type' => 'string', 'default' => '' ),
            'marginTop'          => array( 'type' => 'string', 'default' => '' ),
            'marginRight'        => array( 'type' => 'string', 'default' => '' ),
            'marginBottom'       => array( 'type' => 'string', 'default' => '' ),
            'marginLeft'         => array( 'type' => 'string', 'default' => '' ),
            'backgroundColor'    => array( 'type' => 'string', 'default' => '' ),
            'backgroundImage'    => array( 'type' => 'string', 'default' => '' ),
            'borderColor'        => array( 'type' => 'string', 'default' => '' ),
            'borderWidth'        => array( 'type' => 'string', 'default' => '' ),
            'borderRadius'       => array( 'type' => 'string', 'default' => '' ),
            'borderStyle'        => array( 'type' => 'string', 'default' => 'solid' ),
            'display'            => array( 'type' => 'string', 'default' => '' ),
            'flexDirection'      => array( 'type' => 'string', 'default' => '' ),
            'justifyContent'     => array( 'type' => 'string', 'default' => '' ),
            'alignItems'         => array( 'type' => 'string', 'default' => '' ),
            'gap'                => array( 'type' => 'string', 'default' => '' ),
            'gridTemplateColumns' => array( 'type' => 'string', 'default' => '' ),
        ),
    ) );
}
add_action( 'init', 'infinity_register_blocks' );

/**
 * Render callback for Infinity Container block
 */
function infinity_container_render_callback( $attributes, $content, $block ) {
    // Le contenu des InnerBlocks est déjà dans $content grâce à InnerBlocks.Content
    // Si vide, essayer de récupérer depuis $block (fallback)
    if ( empty( $content ) ) {
        if ( ! empty( $block->inner_html ) ) {
            $content = $block->inner_html;
        } elseif ( ! empty( $block->inner_blocks ) ) {
            $content = '';
            foreach ( $block->inner_blocks as $inner_block ) {
                $content .= render_block( $inner_block );
            }
        }
    }

    // Include the render template
    ob_start();
    include INFINITY_DIR . '/inc/blocks/infinity-container/render.php';
    return ob_get_clean();
}
